### ISSUE TITLE
Model is not a constructor - TypeError

### ISSUE THREAD

**Issue by doverradio** [joegoldbeck/mongoose-encryption#112]
I am trying to use this package and got an error when attempting to create my first encrypted document:
```
TypeError: Customers is not a constructor
```

The JSON data I'm trying to test with:
```
{
    "firstName": "Bob",
    "lastName": "Saget",
    "fullName": "Bob Saget",
    "streetAddress": "389 N. Palm Dr.",
    "extendedAddress": "Unit 3"
}
```

Here is my schema:
```
const mongoose = require("mongoose");
const Schema = mongoose.Schema;
const { ObjectId } = mongoose.Schema;
var encrypt = require('mongoose-encryption');

const customersSchema = new mongoose.Schema(
  {
    firstName: {
      type: String,
      default: ''
    },
    lastName: {
      type: String,
      default: ''
    },
    fullName: {
      type: String,
      default: ''
    },
    streetAddress: {
      type: String,
      default: ''
    },
    extendedAddress: {
      type: String,
      default: ''
    },
    city: {
      type: String,
      default: ''
    },
    state: {
      type: String,
      default: ''
    },
    zip: {
      type: String,
      default: ''
    },
    customerType: {
      type: String,
      default: null
    },
    user: {
      type: ObjectId,
      ref: "User"
    },
    nextActivity: {
      type: String,
      default: null
    },
    total: { type: Number },
    status: {
      type: String,
      default: "Sales Order",
      enum: [
        "Sales Order", 
        "Quotation",
      ] // enum means string objects
    },
  },
  { timestamps: true }
);

var encKey = process.env.SOME_32BYTE_BASE64_STRING;
var sigKey = process.env.SOME_64BYTE_BASE64_STRING;

customersSchema.plugin(encrypt, { encryptionKey: encKey, signingKey: sigKey });
// This adds _ct and _ac fields to the schema, as well as pre 'init' and pre 'save' middleware,
// and encrypt, decrypt, sign, and authenticate instance methods


mongoose.model("Customers", customersSchema, 'customers');

```

I am using `Express.js` and my controller looks like this:
```
const Customers = require('../models/customers')
const log = console.log


exports.createCustomer = async ( req, res ) =>
{
    log( `Beginning createCustomer! Here's req.body: `, req.body )
    let a = {}
    try {
        a.new_customer = new Customers( req.body )
        a.new_customer_doc = await a.new_customer.save().catch( err => log( `a.new_customer.save err: `, err ) )
        res.json( a.new_customer_doc )
    } catch ( e ) {
        log( `createCustomer e: `, e )
        res.status( 400 ).json( { error: e } )
    }
}

```

Upon making the request, I was expecting to see a new encrypted document in MongoDB.  Unfortunately, I got this error:
```
Beginning createCustomer! Here's req.body:  {
  firstName: 'Bob',
  lastName: 'Saget',
  fullName: 'Bob Saget',
  streetAddress: '389 N. Palm Dr.',
  extendedAddress: 'Unit 3'
}
createCustomer e:  TypeError: Customers is not a constructor
    at exports.createCustomer (C:\Users\User\Desktop\project\backend\controllers\customers.js:12:26)
    at Layer.handle [as handle_request] (C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\index.js:275:10)
    at C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\index.js:635:15
    at next (C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\index.js:260:14)
    at Function.handle (C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\index.js:317:13)
    at C:\Users\User\Desktop\project\backend\node_modules\express\lib\router\index.js:284:7
```

Even further, I tried to add this code which did nothing to change the error:
```
// function to generate salt
var genRandomString = function(length){
  return crypto.randomBytes(Math.ceil(length/2))
          .toString('hex') /** convert to hexadecimal format */
          .slice(0,length);   /** return required number of characters */
};

var sha512 = function(password, salt){
  var hash = crypto.createHmac('sha512', salt); /** Hashing algorithm sha512 */
  hash.update(password);
  var value = hash.digest('hex');
  return {
      salt:salt,
      passwordHash:value
  };
}; 

function saltHashPassword(userpassword) {
  var salt = genRandomString(16); /** Gives us salt of length 16 */
  var passwordData = sha512(userpassword, salt);
  console.log('UserPassword = '+userpassword);
  console.log('Passwordhash = '+passwordData.passwordHash);
  console.log('\nSalt = '+passwordData.salt);
}

customersSchema.plugin(mongooseFieldEncryption, { 
  fields: ["streetAddress", "fullName"], 
  secret: encKey, // "some secret key",
  saltGenerator: function ( secret ) {
    var salt = genRandomString(16); /** Gives us salt of length 16 */
    console.log( `salt: `, salt )
    var data = sha512(secret, salt);
    console.log( `data: `, data )
    return data
  },
});
```

Why is it saying the `Customers` model is not a constructor?

How do I solve this?

**Comment by doverradio** [comment]
Awesome, embarassingly, I realized I forgot adding `module.exports =` to my model file.

After adding this, everything worked as expected.  

Thank you so much for creating this package/library!
