### ISSUE TITLE
Authentication failing on subdocuments

### ISSUE THREAD

**Issue by dwichman** [joegoldbeck/mongoose-encryption#14]
Using mongoose-encryption 1.0.1 and I'm trying to encrypt fields in a subdocument following the example in the documents.  Save works okay, but when I do a findById I get an authentication error:

```javascript
Error: Authentication failed
    at Object.schema.methods.authenticateSync (/Users/i816396/Development/eclipse-bootstrap/rental-props/node_modules/mongoose-encryption/index.js:434:15)
    at model.<anonymous> (/Users/i816396/Development/eclipse-bootstrap/rental-props/node_modules/mongoose-encryption/index.js:252:39)
    at model._next (/Users/i816396/Development/eclipse-bootstrap/rental-props/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:62:30)
    at model.proto.(anonymous function) [as $__original_init] (/Users/i816396/Development/eclipse-bootstrap/rental-props/node_modules/mongoose/node_modules/hooks-fixed/hooks.js:108:20)
    at model.wrappedPointCut [as init] (/Users/i816396/Development/eclipse-bootstrap/rental-props/node_modules/mongoose/lib/document.js:1556:21)
    at completeOne (/Users/i816396/Development/eclipse-bootstrap/rental-props/node_modules/mongoose/lib/query.js:1462:10)
    at Object.<anonymous> (/Users/i816396/Development/eclipse-bootstrap/rental-props/node_modules/mongoose/lib/query.js:1200:13)
    at Object._onImmediate (/Users/i816396/Development/eclipse-bootstrap/rental-props/node_modules/mongoose/node_modules/mquery/lib/utils.js:137:16)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

The record is created in mongo:

```
> db.myusers.find().pretty()
{
	"_id" : ObjectId("5554be534f01d2ab466c5faf"),
	"_ac" : BinData(0,"YbX6BvDxN1udTr9vXgIwW/4W2fKMKVDA+JqVFx5mXoB6WyJsb2NhdGlvbnNPZkdvbGQiLCJfaWQiLCJfY3QiXQ=="),
	"_ct" : BinData(0,"YWHNAfYmSKdkmGskvkKlYqFapYLvL7RIhzVgjoRM1A8V"),
	"name" : "foo",
	"locationsOfGold" : [
		{
			"_ct" : BinData(0,"YfuKQ1dJU1J+E12l+fE+sFdPgxexEGlzPnrC2jG61YyOOqc02/PxNdHYNMWdqtUihA=="),
			"nickname" : "bar",
			"_id" : ObjectId("5554be534f01d2ab466c5fb0")
		}
	],
	"__v" : 0
}
```

Here's the code I'm trying to execute based on the doc example:

```javascript
var mongoose = require('mongoose');
var encrypt = require('mongoose-encryption');

var encKey = process.env.RENTAL_ENC_KEY;
var sigKey = process.env.RENTAL_SIG_KEY;

var hidingPlaceSchema = new mongoose.Schema({
  latitude: Number,
  longitude: Number,
  nickname: String
});
 
hidingPlaceSchema.plugin(encrypt, {
  encryptionKey: encKey,
  signingKey: sigKey,
  excludeFromEncryption: ['nickname']
});
 
var userSchema = new mongoose.Schema({
  name: String,
  locationsOfGold: [hidingPlaceSchema]
});
 
// optional but recommended: authenticate subdocuments from the parent document
userSchema.plugin(encrypt, {
  encryptionKey: encKey,
  signingKey: sigKey,
  additionalAuthenticatedFields: ['locationsOfGold'],
  encryptedFields: []
});
 
// optional. only needed for correct document behavior following validation errors during a save
userSchema.plugin(encrypt.encryptedChildren);

MyUser = mongoose.model('MyUser', userSchema);

var myUser = new MyUser({
    name : 'foo',
    locationsOfGold : [{latitude: 1, longitude: 1, nickname: 'bar'}]
});

myUser.save(function(err, myUser) {
    if (err) {
        console.log('err: %s', err.stack);
    } else {
        console.log('created user: %j', myUser);

        MyUser.findById(myUser._id, function(err, myFoundUser) {
            if (err) {
                console.log('find err: %s', err.stack);
            } else {
                console.log('found user: %j', myFoundUser);
            }
        });
    }
});
```

**Comment by joegoldbeck** [comment]
What version of Mongoose are you using? I'm wondering if this could be related to #12.

**Comment by dwichman** [comment]
Yes, looks like.  Was using 4.0.1.  Tried with 3.8.28 and no authentication error now.

Thanks.

**Comment by joegoldbeck** [comment]
Btw, Mongoose 4.x is now supported starting with mongoose-encryption v1.2
