### ISSUE TITLE
Failing Test on Node v4.1.0

### ISSUE THREAD

**Issue by lafama** [joegoldbeck/mongoose-encryption#28]
Am getting the following
```
document.save() "before each" hook:
     Uncaught TypeError: Not a buffer
    at TypeError (native)
    at new Decipheriv (crypto.js:235:16)
    at Object.Decipheriv (crypto.js:232:12)
    at model.schema.methods.decryptSync (/Users/Downloads/mongoose-encryption-master/index.js:379:27)
    at Function.invoke (/Users/Downloads/mongoose-encryption-master/node_modules/sinon/lib/sinon/spy.js:156:55)
    at model.proxy [as decryptSync] (/Users/Downloads/mongoose-encryption-master/node_modules/sinon/lib/sinon/spy.js:82:26)
    at model.<anonymous> (/Users/Downloads/mongoose-encryption-master/index.js:312:17)
    at EventEmitter.<anonymous> (/Users/Downloads/mongoose-encryption-master/node_modules/mongoose/lib/schema.js:781:17)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at model.Document.(anonymous function) [as emit] (/Users/Downloads/mongoose-encryption-master/node_modules/mongoose/lib/document.js:88:42)
    at /Users/Downloads/mongoose-encryption-master/node_modules/mongoose/lib/model.js:268:13
    at /Users/Downloads/mongoose-encryption-master/node_modules/mongoose/lib/model.js:127:7
    at /Users/Downloads/mongoose-encryption-master/node_modules/mongodb/lib/collection.js:449:5
    at /Users/Downloads/mongoose-encryption-master/node_modules/mongodb/lib/collection.js:593:5
    at /Users/Downloads/mongoose-encryption-master/node_modules/mongodb/lib/bulk/unordered.js:457:9
    at resultHandler (/Users/Downloads/mongoose-encryption-master/node_modules/mongodb/lib/bulk/unordered.js:409:5)
    at /Users/Downloads/mongoose-encryption-master/node_modules/mongodb-core/lib/topologies/server.js:756:13
    at [object Object].Callbacks.emit (/Users/Downloads/mongoose-encryption-master/node_modules/mongodb-core/lib/topologies/server.js:95:3)
    at [object Object].messageHandler (/Users/Downloads/mongoose-encryption-master/node_modules/mongodb-core/lib/topologies/server.js:243:23)
    at Socket.<anonymous> (/Users/Downloads/mongoose-encryption-master/node_modules/mongodb-core/lib/connection/connection.js:262:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
``

**Comment by fantasy8-me** [comment]
same here, when can we have node.js v4 support, thanks

**Comment by simonpure** [comment]
ditto, thanks!

**Comment by BDiehr** [comment]
+1

**Comment by colinhemphill** [comment]
+1

**Comment by BrandonCopley** [comment]
+1

On Thu, Oct 22, 2015 at 4:56 PM, Colin <notifications@github.com> wrote:

> +1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joegoldbeck/mongoose-encryption/issues/28#issuecomment-150367512>
> .
>



-- 
[image: Giftnix]

Brandon Copley

Founder & CEO

t: 512.784.6060

e: copley.brandon@gmail.com

**Comment by joegoldbeck** [comment]
Node v4 support is key. I should have some time to take a look first week of November and hopefully it won't be too bad a fix. Happy to review any PRs if someone has time to track it down before then :)

**Comment by BDiehr** [comment]
This will probably be solved by simply updating the dependencies. I'll take a quick stab at it this weekend

**Comment by foster** [comment]
@joegoldbeck @BDiehr The left side of this expression will always evaluate truthy:

    ctWithIV = this._ct.buffer || this._ct;

From the node v4 release notes,
> Node's Buffer is now backed by Uint8Array

... so now all `Buffer` objects have a `.buffer` inherited [from its prototype](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array).

The new line should be something more like this:

        ctWithIV = this._ct.hasOwnProperty('buffer') ?  this._ct.buffer : this._ct;

I'm out of time today. After fixing the `ctWithIV` and `acBuf` lines, 3 tests still fail. I can try to get through them tomorrow and PR if nobody else gets to it first.

**Comment by deepakc** [comment]
Fails from Node v3.0.0
From v3.0.0 release notes - https://github.com/nodejs/node/blob/v3.0.0/CHANGELOG.md
```"Due to changes in V8, it has been necessary to reimplement Buffer on top of V8's Uint8Array"```

**Comment by foster** [comment]
I think the remaining tests are broken due to Buffer handling in mongoose.
Automattic/mongoose#3496

**Comment by joegoldbeck** [comment]
Should be fixed as of plugin version 1.2.2 with Mongoose version 4.2.4. Still need to throw an error when that criteria isn't met, but otherwise the failing behavior should be fixed.

**Comment by molekilla** [comment]
hi, can you update changelog.md with 1.2.2 ? tks!

**Comment by joegoldbeck** [comment]
oops, forgot to push. done!
