### ISSUE TITLE
Im getting this error after updating mongoose.

### ISSUE THREAD

**Issue by muhammadfaizan** [joegoldbeck/mongoose-encryption#62]
```
2017-07-20T13:22:25.068975+00:00 app[web.1]: > app@2.11.0 start /app
2017-07-20T13:22:25.068976+00:00 app[web.1]: > node ./bin/www
2017-07-20T13:22:25.068977+00:00 app[web.1]:
2017-07-20T13:22:26.261157+00:00 app[web.1]:     throw new TypeError('Invalid Version: ' + version);
2017-07-20T13:22:26.261158+00:00 app[web.1]:     ^
2017-07-20T13:22:26.261146+00:00 app[web.1]: /app/node_modules/mongoose-encryption/node_modules/semver/semver.js:293
2017-07-20T13:22:26.261159+00:00 app[web.1]:
2017-07-20T13:22:26.261160+00:00 app[web.1]: TypeError: Invalid Version: https://registry.npmjs.org/mongoose/-/mongoose-4.4.20.tgz
2017-07-20T13:22:26.261161+00:00 app[web.1]:     at new SemVer (/app/node_modules/mongoose-encryption/node_modules/semver/semver.js:293:11)
2017-07-20T13:22:26.261161+00:00 app[web.1]:     at compare (/app/node_modules/mongoose-encryption/node_modules/semver/semver.js:566:10)
2017-07-20T13:22:26.261162+00:00 app[web.1]:     at Function.lt (/app/node_modules/mongoose-encryption/node_modules/semver/semver.js:600:10)
2017-07-20T13:22:26.261163+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/mongoose-encryption/index.js:74:15)
2017-07-20T13:22:26.261163+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/mongoose-encryption/index.js:592:4)
2017-07-20T13:22:26.261164+00:00 app[web.1]:     at Module._compile (module.js:569:30)
2017-07-20T13:22:26.261165+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:580:10)
2017-07-20T13:22:26.261166+00:00 app[web.1]:     at Module.load (module.js:503:32)
2017-07-20T13:22:26.261166+00:00 app[web.1]:     at tryModuleLoad (module.js:466:12)
2017-07-20T13:22:26.261167+00:00 app[web.1]:     at Function.Module._load (module.js:458:3)
2017-07-20T13:22:26.261167+00:00 app[web.1]:     at Module.require (module.js:513:17)
2017-07-20T13:22:26.261169+00:00 app[web.1]:     at Object.<anonymous> (/app/db-handle/model/person.js:9:17)
2017-07-20T13:22:26.261168+00:00 app[web.1]:     at require (internal/module.js:11:18)
2017-07-20T13:22:26.261170+00:00 app[web.1]:     at Module._compile (module.js:569:30)
2017-07-20T13:22:26.261170+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:580:10)
2017-07-20T13:22:26.261171+00:00 app[web.1]:     at Module.load (module.js:503:32)
2017-07-20T13:22:26.278163+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2017-07-20T13:22:26.278299+00:00 app[web.1]: npm ERR! errno 1
2017-07-20T13:22:26.278471+00:00 app[web.1]: npm ERR! Exit status 1
2017-07-20T13:22:26.278397+00:00 app[web.1]: npm ERR! app@2.11.0 start: `node ./bin/www`
2017-07-20T13:22:26.278596+00:00 app[web.1]: npm ERR!
2017-07-20T13:22:26.278673+00:00 app[web.1]: npm ERR! Failed at the app@2.11.0 start script.
2017-07-20T13:22:26.278755+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

Can You please help me resolve this. Im using mongoose : 4.4.20

**Comment by joegoldbeck** [comment]
It would appear that the particular version of Mongoose you're using exposes its version as "https://registry.npmjs.org/mongoose/-/mongoose-4.4.20.tgz", rather than semver number (i.e. 4.4.20)

I'd propose either

1) Upgrading to a newer version of Mongoose which hopefully doesn't have that problem
2) Monkey-patch Mongoose before the `require 'mongoose-encryption'` statement. Specifically, set `mongoose.version` to `4.4.20`.

**Comment by muhammadfaizan** [comment]
Yes it was the issue with mongoose version itself. I upgraded it further.
