### ISSUE TITLE
Question about encryption

### ISSUE THREAD

**Issue by Themandunord** [joegoldbeck/mongoose-encryption#69]
Hi,

I have a DB with a previous collection that has been encrypted with the KEY_A.
My collegue change the KEY with B.

So when I want to get the documents from the collection, I have this error : 
```
 Error: Authentication failed
[1]     at Object.schema.methods.authenticateSync (d:\30_AIFE\Source\chorus-aife-code\node_modules\mongoose-encryption\lib\plugins\mongoose-encryption.js:466:19)
[1]     at model.<anonymous> (d:\30_AIFE\Source\chorus-aife-code\node_modules\mongoose-encryption\lib\plugins\mongoose-encryption.js:244:47)
[1]     at model._next (d:\30_AIFE\Source\chorus-aife-code\node_modules\hooks-fixed\hooks.js:63:32)
[1]     at model.proto.(anonymous function) [as $__original_init] (d:\30_AIFE\Source\chorus-aife-code\node_modules\hooks-fixed\hooks.js:112:20)
[1]     at d:\30_AIFE\Source\chorus-aife-code\node_modules\mongoose\lib\services\model\applyHooks.js:161:27
[1]     at new Promise (<anonymous>)
[1]     at model.wrappedPointCut [as init] (d:\30_AIFE\Source\chorus-aife-code\node_modules\mongoose\lib\services\model\applyHooks.js:139:23)
[1]     at completeMany (d:\30_AIFE\Source\chorus-aife-code\node_modules\mongoose\lib\query.js:1425:12)
[1]     at Immediate.cb (d:\30_AIFE\Source\chorus-aife-code\node_modules\mongoose\lib\query.js:1290:13)
[1]     at Immediate._onImmediate (d:\30_AIFE\Source\chorus-aife-code\node_modules\mquery\lib\utils.js:137:16)
[1]     at runCallback (timers.js:789:20)
[1]     at tryOnImmediate (timers.js:751:5)
[1]     at processImmediate [as _immediateCallback] (timers.js:722:5) '[api\\classification\\classification.controller.js:146:12]'
```

So I can't get the content of the data because we don't use the same key.

But how to don't throw this error when we execute a query ?

Thanks.

**Comment by joegoldbeck** [comment]
Hi @Themandunord. The plugin currently only supports a single key, and does not have key rotation as an explicit feature. There are a couple ways to achieve key rotation, however, as noted in this issue: https://github.com/joegoldbeck/mongoose-encryption/issues/49

If you want to use two keys _in parallel_, my recommendation would be to use two collections, (one for each key). There _may_ also be a way to do a similar thing by using [discriminators](http://mongoosejs.com/docs/discriminators.html), which allow for two schemas to exists side by side within a single collection.
