### ISSUE TITLE
Authenticate issues from implementing mongoose-encryption

### ISSUE THREAD

**Issue by banandam** [joegoldbeck/mongoose-encryption#76]
Authentication purpose we used passport plugin. (https://github.com/jaredhanson/passport). Now we are implementing mongoose-encryption. we have face below issue. let me know what is the problem ? 

```
{ _csrf: 'ckRqJNSz-OaPeqLE0-5voVodd_mgOHZCuW4U',
  role: '',
  email: 'anandam.b+user5@gmail.com',
  password: 'Test@123' }
(node:3425) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: cb is not a function
    at model.schema.methods.authenticate (/usr/share/nginx/html/sns-Marketplace/node_modules/mongoose-encryption/lib/plugins/mongoose-encryption.js:441:20)
    at /usr/share/nginx/html/sns-Marketplace/node_modules/passport-local-mongoose/lib/passport-local-mongoose.js:203:33
    at /usr/share/nginx/html/sns-Marketplace/node_modules/mongoose/lib/query.js:3118:18
    at newTickHandler (/usr/share/nginx/html/sns-Marketplace/node_modules/mpromise/lib/promise.js:234:18)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

```

**Comment by joegoldbeck** [comment]
Hi @banandam I wonder if it's a Mongoose version issue? If you're relying on Mongoose 5.x, please try the newly published `2.x` version

**Comment by joegoldbeck** [comment]
Closing due to inactivity
