### ISSUE TITLE
Error: Authentication failed

### ISSUE THREAD

**Issue by dyarfaradj** [joegoldbeck/mongoose-encryption#86]
> "mongoose": "^5.4.21",
    "mongoose-encryption": "^2.0.2",

I get this error: 

> Error: Authentication failed
    at Object.schema.methods.authenticateSync (D:\Documents\GitHub\projektkurs\node_modules\mongoose-encryption\lib\plugins\mongoose-encryption.js:436:19)
    at model.<anonymous> (D:\Documents\GitHub\projektkurs\node_modules\mongoose-encryption\lib\plugins\mongoose-encryption.js:239:47)

````
const mongoose = require("mongoose");
const encrypt = require('mongoose-encryption');

const newsSchema = mongoose.Schema({
  title: { type: String, required: true, max: 100},
  text: {type: String, required: true, max: 100},
  image: {type: String, required: true, max: 100},
  date: {type: Date, required: true},
  ssn: {type: String, required: true, max: 12},
});

const encKey = process.env.encryptionKEY;
const sigKey = process.env.signatureKEY;
newsSchema.plugin(encrypt, { requireAuthenticationCode: false, encryptionKey: encKey, signingKey: sigKey });

const News = mongoose.model("News", newsSchema, "news");
module.exports = News;
```
In the database it saves it like this:
```
`{
    "_id" : ObjectId("5cddcbbb42d8e00c70427d85"),
    "_ct" : { "$binary" : "YegsmTn1zgLUi2gWsVsyxoQ4rojaEX384/T/VraauZDNytN+evSBQEzlizddjVH8409SbfSqj/2YWGnz2GXvwgbhgo27xscEcyP0TaD3zgOmj/F+Uxg5q3/90Q2bgYqKy4xMpAiTeaaDJ7go4ybLbnQ9k7EOn+cyFO4iDlOqLT9o", "$type" : "00" },
    "_ac" : { "$binary" : "YW8ta8BEuJMcLyw0NxB5S3CQtaDZ2bmXkW62jaokdDrVWyJfaWQiLCJfY3QiXQ==", "$type" : "00" },
    "__v" : 0
}`
```

**Comment by joegoldbeck** [comment]
Thanks for the filing this issue @dyarfaradj .  Your code all looks correct, so this seems odd! What versions of Node and MongoDB are you using?

**Comment by dyarfaradj** [comment]
@joegoldbeck I'm using cloud mongodb latest version 4.0.9 and latest version of node.js

**Comment by joegoldbeck** [comment]
Can you be more specific about the version of node.js? Specifically, what does `node --version` output?

**Comment by dyarfaradj** [comment]
> node --version

Gives me v11.13.0

**Comment by joegoldbeck** [comment]
Ok! Would you be willing/able to try running it with something on the Node 10.x line? 

Node 10.x is the current long term support (LTS) release

Node 11 is the _older_ release line and no longer supported since end of April https://medium.com/@nodejs/october-brings-node-js-10-x-to-lts-and-node-js-11-to-current-ae19f8f12b51

Node 12 is the _current_ release line, and will be LTS in October.

If your code is working on Node 10, but then failing on Node 12, that would be great to know since that would mean we don't support yet the upcoming LTS line, and ideally we should get ahead of that.

If it's not working even on Node 10 that would be _especially_ good to know!

**Comment by joegoldbeck** [comment]
Closing due to lack of activity
