### ISSUE TITLE
Encrypt failed: document already contains ciphertext

### ISSUE THREAD

**Issue by ThBM** [joegoldbeck/mongoose-encryption#89]
Hello,

I have the following mongoose schema which is work fine. However, since I added mongoose-encryption plugin, I have an error (see below).

```typescript
import Mongoose from "../services/Mongoose";
import {IJob} from "./Job";
import {IOccurrence, OccurrenceSchema} from "./Occurrence";
import {config} from "../config";
const mongooseEncryption = require("mongoose-encryption");

export interface IDocument extends Mongoose.Document {
  job: IJob
  filename: string
  path: string
  title: string
  notes: string
  workdone: string
  conclusion: string
  pending: boolean
  pendingComments?: string
  occurrences: Mongoose.Types.DocumentArray<IOccurrence>
  xref?: string
}

export const DocumentSchema = new Mongoose.Schema({
  filename: {
    type: String,
    required: true
  },
  path: {
    type: String,
    required: true
  },
  title: {
    type: String,
    default: ""
  },
  notes: {
    type: String,
    default: ""
  },
  workdone: {
    type: String,
    default: ""
  },
  conclusion: {
    type: String,
    default: ""
  },
  pending: {
    type: Boolean,
    default: false
  },
  pendingComments: {
    type: String,
    default: ""
  },
  occurrences: [OccurrenceSchema]
});

DocumentSchema.plugin(mongooseEncryption, {
  secret: "helloworld",
  encryptedFields: ["notes", "workdone", "conclusion"]
});

const Document = Mongoose.model<IDocument>('Document', DocumentSchema);
export default Document;
```

The error :
```
api_1            | (node:86) UnhandledPromiseRejectionWarning: Error: Encrypt failed: document already contains ciphertext
api_1            |     at EmbeddedDocument.schema.methods.encrypt (/app/node_modules/mongoose-encryption/lib/plugins/mongoose-encryption.js:320:23)
api_1            |     at EmbeddedDocument.<anonymous> (/app/node_modules/mongoose-encryption/lib/plugins/mongoose-encryption.js:268:22)
api_1            |     at callMiddlewareFunction (/app/node_modules/kareem/index.js:482:23)
api_1            |     at EmbeddedDocument.next (/app/node_modules/kareem/index.js:58:7)
api_1            |     at _next (/app/node_modules/kareem/index.js:106:10)
api_1            |     at /app/node_modules/kareem/index.js:507:38
api_1            |     at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

Am I doing the wrong way?

Thanks in advance for your help.

Theud.

**Comment by joegoldbeck** [comment]
Hi @ThBM! Thanks for reaching out.

That is odd! The code you showed looks correct. What are you trying to do when the error occurs? Can you show me the code leading up to the error? Perhaps there's something there that's not expected.

Thanks!
Joe

**Comment by ThBM** [comment]
Hi,

Sorry to be ~~very~~ late.
I found what was happening: between the moment I query my Document and the moment I save it, some changes occurred on the same Document somewhere else in the process.
As a workaround, I query again my Document just before saving the changes.

Have a nice day!

ThBM
